environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python36-x64"

build: off

install:
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"

test_script:
  - "%PYTHON%/Scripts/pytest.exe"
